version: '3.8'

services:
  app:
    container_name: chatimageclassifier
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - CATALOG_ID
      - YANDEX_API_KEY