[tool.poetry]
name = "test-vibe"
version = "0.1.0"
description = ""
authors = ["Kirill <litvinka@my.msu.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
